### PR TITLE
Fix #24: geodsolve28

### LINKED ISSUE #24: fix test_std_geodesic_geodsolve28 failure
This standard Karney unit test currently fails. Fix geodesic to make it work.

It tests arc-distance for a case with large-ish flattening (0.1).

### PR DESCRIPTION
**Pull request by stonylohr**
Also updated and enabled some geodtest cases related to GeodesicLine position.
Fixes improve behavior of test_arcdirect, but not enough to make it pass.

- [ ] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

File: src/geodesicline.rs [hunk 1]
```diff
@@ -230,16 +229,10 @@ impl GeodesicLine {
             sig12 = s12_a12.to_radians();
             let res = geomath::sincosd(s12_a12);
             ssig12 = res.0;
-            csig12 = res.0;
+            csig12 = res.1;
```
Comment (michaelkirk) [inline src/geodesicline.rs:232]: good find! 

One day the [destructuring assignment RFC](https://rust-lang.github.io/rfcs/2909-destructuring-assignment.html) may prevent bugs like this by letting us write:

```
// assign to existing `mut` vars
(ssig12, csig12) = geomath::sincosd(s12_a12);
```

File: src/geodesicline.rs [hunk 2]
```diff
@@ -258,7 +251,7 @@ impl GeodesicLine {
                 csig2 = self._csig1 * csig12 - self._ssig1 * ssig12;
                 B12 = geomath::sin_cos_series(true, ssig2, csig2, &self._C1a);
                 let serr = (1.0 + self._A1m1) * (sig12 + (B12 - self._B11)) - s12_a12 / self._b;
-                sig12 = sig12 - serr / (1.0 + self._k2 * ssig2.sqrt()).sqrt();
+                sig12 = sig12 - serr / (1.0 + self._k2 * geomath::sq(ssig2)).sqrt();
```
Comment (michaelkirk) [inline src/geodesicline.rs:254]: good find!

File: src/geodesicline.rs [hunk 3]
```diff
@@ -78,15 +78,14 @@ impl GeodesicLine {
...
-        let lon1 = lon1;
         let (azi1, salp1, calp1) = if salp1.is_nan() || calp1.is_nan() {
-            let (salp1, calp1) = geomath::sincosd(geomath::ang_round(azi1));
             let azi1 = geomath::ang_normalize(azi1);
+            let (salp1, calp1) = geomath::sincosd(geomath::ang_round(azi1));
             (azi1, salp1, calp1)
         } else {
             (azi1, salp1, calp1)
         };
+        let lat1 = geomath::lat_fix(lat1);
```
Comment (michaelkirk) [inline src/geodesicline.rs:88]: Why did this line move? Is it functionally significant?

File: src/geodesicline.rs [hunk 4]
```diff
@@ -19,8 +19,8 @@ pub struct GeodesicLine {
     _C1a: [f64; GEODESIC_ORDER as usize + 1],
     _C1pa: [f64; GEODESIC_ORDER as usize + 1],
     _C2a: [f64; GEODESIC_ORDER as usize + 1],
-    _C3a: [f64; GEODESIC_ORDER as usize + 1],
-    _C4a: [f64; GEODESIC_ORDER as usize + 1],
+    _C3a: [f64; GEODESIC_ORDER as usize],
```
Comment (michaelkirk) [inline src/geodesicline.rs:22]: nice!

File: src/geodesic.rs [hunk 5]
```diff
@@ -2235,26 +2234,24 @@ mod tests {
...
         assert_approx_eq!(azi2, -170.0, 1.0);
 
-        // GeodesicLine.position doesn't appear to be supported in geographiclib-rs as of 2021/01/18
-        // let line = geod.line(40.0, -75.0, -10.0);
-        // let (_a12, lat2, lon2, azi2, _s12, _m12, _M12, _M21, _S12) =
-        //     line.position(2e7, caps::STANDARD | caps::LONG_UNROLL);
-        // assert_approx_eq!(lat2, -39.0, 1.0);
-        // assert_approx_eq!(lon2, -254.0, 1.0);
-        // assert_approx_eq!(azi2, -170.0, 1.0);
+        let line = GeodesicLine::new(&geod, 40.0, -75.0, -10.0, None, None, None);
```
Comment (michaelkirk) [inline src/geodesic.rs:2237]: 🎉

File: src/geodesic.rs [hunk 6]
```diff
@@ -914,11 +917,6 @@ impl Geodesic {
         if !arcmode {
             outmask = outmask | caps::DISTANCE_IN;
         };
-        let lon1 = if outmask & caps::LONG_UNROLL != 0 {
```
Comment (michaelkirk) [inline src/geodesic.rs:917]: I guess this is redundant here because Karney had added duplicate behavior in `GeodesicLine`... right?

**Review by michaelkirk — APPROVED** [review]
Looks great, thank you!

Again, my method of evaluation was to just visually compare your changes to what exists in karney's implementation.

(and seeing the tests pass 😃)

File: src/geodesicline.rs (hunk 1 above)
Comment (stonylohr) [reply src/geodesicline.rs:232]: Yes, I've been looking forward to destructuring assignment for a while. I think it will let us make the code quite a bit cleaner-looking in places.

File: src/geodesicline.rs (hunk 3 above)
Comment (stonylohr) [reply src/geodesicline.rs:88]: This is one of a few places where the C++ code did things in a different order, where I opted to go with the C++. Part of my reasoning is that I expect to be back through this code again in the near future, for example for test_arcdirect, and sticking closer to the C++ will make that later pass a little easier. I did think about highlighting this as a more marginal change than the more obviously clear-cut cases. If you'd prefer a different approach in these cases in the future, I can try to remember to highlight them in the initial pull request or whatever.

File: src/geodesic.rs (hunk 6 above)
Comment (stonylohr) [reply src/geodesic.rs:917]: Exactly. This is another case where the tip-off was that the C++ code didn't bother with it here. This is a case where the old difference almost certainly did no harm other than slight performance overhead, but I'm just sort of gradually shifting things toward the C++ approach.

File: src/geodesicline.rs (hunk 3 above)
Comment (michaelkirk) [reply src/geodesicline.rs:88]: If it's just one or two lines like this it's fine - I just wanted to make sure I was understanding. 

If it's a larger cosmetic change, for purposes of archeology, I prefer to have no-op changes in a separate commit. In the future if we need to `git bisect` or something it's often helpful to understand what changes are intended to be significant.
