### PR TITLE
fix #25: geodsolve29.

### LINKED ISSUE #25: fix test_std_geodesic_geodsolve29 failure
This standard Karney unit test currently fails. Fix geodesic to make it work.

Tests longitude unrolling with inverse calculation. It also happens to use a large-ish flattening (0.1), though the test description doesn't highlight that.

### PR DESCRIPTION
**Pull request by stonylohr**
Test was using wrong ellipsoid, due to copy-paste error.

- [ ] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]
bors r+

nice!

File: src/geodesic.rs [hunk 1]
```diff
@@ -2258,10 +2258,9 @@ mod tests {
...
 
     #[test]
-    #[ignore] // Fails existing behavior.
     fn test_std_geodesic_geodsolve29() {
         // Check longitude unrolling with inverse calculation 2015-09-16
-        let geod = Geodesic::new(6.4e6, 0.1);
+        let geod = Geodesic::wgs84();
         let (_a12, s12, _salp1, _calp1, _salp2, _calp2, _m12, _M12, _M21, _S12) =
             geod._gen_inverse(0.0, 539.0, 0.0, 181.0, caps::STANDARD);
         // Note: This is also supposed to check adjusted longitudes, but geographiclib-rs
```
Comment (michaelkirk) [inline src/geodesic.rs:2266]: I guess this portion of the test is still TODO. 

By "adjusted longitude" - is that the same thing as feature enabled by the `LONG_UNROLL` flag, or is this something else?

Comment (stonylohr) [reply src/geodesic.rs:2266]: Right, that part is still todo. It's checking an output that's included in Java, but not in C++. I don't remember how closely it's related to the LONG_UNROLL flag, but it comes down to providing adjusted versions of some inputs as outputs. Of course, it's possible that I'm currently missing a straightforward way to request the comparable value in C++ -- I haven't taken a very close look. Regardless, I don't expect to revisit that any time in the immediate future. We've got lots of bigger issues to chase down first.
